### ISSUE TITLE
Run buffalo updatex

### ISSUE THREAD

**Issue by jordan-rash** [fdonzello/go-with-jwt#1]
Hey, I find your tutorial and this project really helpful.  I thought I would recommend you run `buffalo updatex` and update the main.go to use `app.Server` as opposed to `app.Start` to have to project work with the newest buffalo version.

If you'd prefer, I can do a PR as I have already done these few steps and have the test working. 
Thanks again!

**Comment by fdonzello** [comment]
Hi Jordan,

yes open a PR, I will be happy to merge it ;)

Thank you!

**Comment by jordan-rash** [comment]
Will do this evening!

**Comment by fdonzello** [comment]
Merged, thanks!
